from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer
)
from datetime import datetime
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.styles import ParagraphStyle


def generate_incident_pdf(data, output_file):

    doc = SimpleDocTemplate(output_file)

    styles = getSampleStyleSheet()
    heading_style = ParagraphStyle(
    "SectionHeading",
    parent=styles["Heading2"],
    fontSize=14,
    leading=18,
    spaceAfter=8
)

    story = []

    story.append(
        Paragraph("PULSE Incident Report", styles["Title"])
    )
    story.append(Paragraph("Prepared For:<br/> Bengaluru Traffic Management Center", styles["Normal"]))
    story.append(Spacer(1,6))
    story.append(
    Paragraph(
        f"Generated by PULSE<br/>"
        f"Predictive Urban Live Situation Engine",
    )
)
    story.append(Spacer(1,6))
    story.append(
    Paragraph(
        f"""
        Report ID: PULSE-{datetime.now().strftime('%Y%m%d-%H%M')}<br/>
        Generated: {datetime.now().strftime('%d-%b-%Y %H:%M')}
        """,
        styles["Italic"]
    )
)


    
    story.append(Spacer(1,6))
    story.append(Paragraph("INCIDENT DETAILS", heading_style))
    story.append(Paragraph(
    f"""
    Incident Type: {data['Incident Type']}<br/>
    Event Type: {data['Event Type']}<br/>
    Corridor: {data['Corridor']}<br/>
    Zone: {data['Zone']}<br/>
    Junction: {data['Junction']}<br/>
    Time: {data['Hour']}:00<br/>
    Road Closure Reported: {data['Road Closure Reported']}
    """,
    styles["Normal"]
))
    story.append(Spacer(1,6))
    
    severity = data["Severity"]

    if severity == "CRITICAL":
       banner = "IMMEDIATE RESPONSE REQUIRED"
    elif severity == "HIGH":
       banner = "HIGH PRIORITY INCIDENT"
    else:
       banner = "STANDARD RESPONSE"

    story.append(
    Paragraph(
        banner,
        heading_style
    )
)
    story.append(Paragraph("AI IMPACT ASSESSMENT", heading_style))
    story.append(Paragraph(
    f"""
    Severity: {data['Severity']}<br/>
    Impact Score: {data['Impact Score']}<br/>
    Congestion Risk: {data['Congestion Risk']}<br/>
    Road Closure Probability: {data['Road Closure Probability']}<br/>
    Estimated Delay: {data['Estimated Delay']}<br/>
    Vehicles Affected: {data['Vehicles Affected']}
    """,
    styles["Normal"]
))
    story.append(Spacer(1,6))
    story.append(
    Paragraph(
        "TRAFFIC RESPONSE ORDER",
        heading_style
    )
)
   
    priority = (
    "CRITICAL"
    if data["Severity"] == "CRITICAL"
    else "HIGH"
)
    story.append(
    Paragraph(
        f"""
        <b>Incident Severity:</b> {data['Severity']}<br/>
        <b>Priority Level:</b> {priority}<br/><br/>

        <b>MANDATORY DEPLOYMENT</b><br/><br/>

        <b>Personnel</b><br/>
        • Traffic Officers Required: {data['Officers Required']}<br/><br/>

        <b>Infrastructure</b><br/>
        • Barricades Required: {data['Barricades Required']}<br/><br/>

        <b>Traffic Operations</b><br/>
        • Diversion Activation: {data['Diversion Required']}<br/><br/>

        <b>Performance Targets</b><br/>
        • Response SLA: 10 Minutes<br/>
        • Estimated Delay: {data['Estimated Delay']}<br/><br/>

        <b>Expected Impact</b><br/>
        • Vehicles Affected: {data['Vehicles Affected']}
        """,
        styles["Normal"]
    )
)

    story.append(Spacer(1,6))

    story.append(
    Paragraph(
        "RESOURCE REQUEST RECOMMENDATION",
        heading_style
    )
)

    story.append(
    Paragraph(
        f"""
        Recommended for Immediate Approval:<br/>

        • {data['Officers Required']} Traffic Officers<br/>
        • {data['Barricades Required']} Barricades<br/>
        • Diversion Plan Activation: {data['Diversion Required']}<br/>

        Operational Justification:<br/>
Predicted congestion risk exceeds acceptable operational thresholds.<br/>
Immediate deployment is recommended to minimize network disruption and maintain traffic flow.
        """,
        styles["Normal"]
    )
)
    story.append(Spacer(1,6))
    story.append(Paragraph("WHY THIS PREDICTION HAPPENED", heading_style))
        

    for driver in data["Prediction Drivers"]:
         story.append(
        Paragraph(
            f"{driver['name']} : +{driver['score']}",
            styles["Normal"]
        )
    )

    story.append(Spacer(1,6))

    story.append(
    Paragraph(
        data["Prediction Explanation"],
        styles["Italic"]
    )
)
        
    story.append(Spacer(1,6))
    story.append(Paragraph("RECOMMENDED ACTIONS", heading_style))

    for idx, action in enumerate(data["Actions"], start=1):
            story.append(
        Paragraph(
            f"{idx}. {action}",
            styles["Normal"]
        )
    )
    story.append(Spacer(1,6))
    story.append(
    Paragraph(
        "SPATIAL RISK ASSESSMENT",
        heading_style
    )
)
    
    junction_risk = (
    "HIGH"
    if data["Junction Frequency"] > 8
    else "MEDIUM"
)

    corridor_risk = (
    "HIGH"
    if data["Corridor Frequency"] > 300
    else "MEDIUM"
)

    hotspot_risk = (
    "HIGH"
    if data["Hotspot Density"] > 20
    else "MEDIUM"
)
    story.append(
    Paragraph(
        f"""
        Junction Risk Level: {junction_risk}<br/>
        Corridor Risk Level: {corridor_risk}<br/>
        Hotspot Activity: {hotspot_risk}
        """,
        styles["Normal"]
    )
)
            
   

    
    story.append(Spacer(1,20))
    story.append(
    Paragraph(
        "CONTROL ROOM AUTHORIZATION",
        heading_style
    )
)

    story.append(Spacer(1,10))
    story.append(
    Paragraph(
        """
        

        Approved By:<br/><br/> _______________________<br/><br/>

        Traffic Operations Officer:<br/><br/> _______________________<br/><br/>

        Signature:<br/><br/> _______________________
        """,
        styles["Normal"]
    )
)
            

    doc.build(story)